// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Card defines model for Card.
type Card struct {
	Back          string             `json:"back"`
	BackImageUrl  *string            `json:"back_image_url,omitempty"`
	CreatedAt     time.Time          `json:"created_at"`
	DeckId        openapi_types.UUID `json:"deck_id"`
	EaseFactor    float64            `json:"ease_factor"`
	Front         string             `json:"front"`
	FrontImageUrl *string            `json:"front_image_url,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	IntervalDays  int                `json:"interval_days"`
	NextReview    time.Time          `json:"next_review"`
	Repetitions   int                `json:"repetitions"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// CreateCardRequest defines model for CreateCardRequest.
type CreateCardRequest struct {
	Back         string              `json:"back"`
	BackImageId  *openapi_types.UUID `json:"back_image_id,omitempty"`
	Front        string              `json:"front"`
	FrontImageId *openapi_types.UUID `json:"front_image_id,omitempty"`
}

// CreateDeckRequest defines model for CreateDeckRequest.
type CreateDeckRequest struct {
	Name       string `json:"name"`
	SourceLang string `json:"source_lang"`
	TargetLang string `json:"target_lang"`
}

// Deck defines model for Deck.
type Deck struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	SourceLang string             `json:"source_lang"`
	TargetLang string             `json:"target_lang"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExerciseCard defines model for ExerciseCard.
type ExerciseCard struct {
	Back  string `json:"back"`
	Front string `json:"front"`
	Id    string `json:"id"`
	Level int    `json:"level"`
}

// ExerciseCompleteRequest defines model for ExerciseCompleteRequest.
type ExerciseCompleteRequest struct {
	Correct    bool   `json:"correct"`
	ExerciseId string `json:"exercise_id"`
	UserAnswer string `json:"user_answer"`
}

// ExerciseGenerateRequest defines model for ExerciseGenerateRequest.
type ExerciseGenerateRequest struct {
	Cards      []ExerciseCard `json:"cards"`
	KnownWords *[]KnownWord   `json:"known_words,omitempty"`
	SessionId  *string        `json:"session_id,omitempty"`
	SourceLang string         `json:"source_lang"`
	TargetLang string         `json:"target_lang"`
}

// ExerciseGradeRequest defines model for ExerciseGradeRequest.
type ExerciseGradeRequest struct {
	CorrectAnswer string  `json:"correct_answer"`
	ExerciseId    *string `json:"exercise_id,omitempty"`
	ExerciseType  *string `json:"exercise_type,omitempty"`
	Prompt        *string `json:"prompt,omitempty"`
	SourceLang    string  `json:"source_lang"`
	TargetLang    string  `json:"target_lang"`
	UserAnswer    string  `json:"user_answer"`
}

// ExerciseResponse defines model for ExerciseResponse.
type ExerciseResponse struct {
	CorrectAnswer  string                  `json:"correct_answer"`
	Data           *map[string]interface{} `json:"data,omitempty"`
	Hint           *string                 `json:"hint,omitempty"`
	Id             string                  `json:"id"`
	Instruction    string                  `json:"instruction"`
	Level          int                     `json:"level"`
	Options        *[]string               `json:"options,omitempty"`
	Prompt         string                  `json:"prompt"`
	SourceCardId   string                  `json:"source_card_id"`
	SourceSentence *string                 `json:"source_sentence,omitempty"`
	Type           string                  `json:"type"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	DeckId         openapi_types.UUID    `json:"deck_id"`
	FromDeck       *bool                 `json:"from_deck,omitempty"`
	GenerateImages *bool                 `json:"generate_images,omitempty"`
	ImageIds       *[]openapi_types.UUID `json:"image_ids,omitempty"`
	Mode           *string               `json:"mode,omitempty"`
	Prompt         *string               `json:"prompt,omitempty"`
	SourceLang     string                `json:"source_lang"`
	TargetLang     string                `json:"target_lang"`
}

// GeneratedCard defines model for GeneratedCard.
type GeneratedCard struct {
	Back             string  `json:"back"`
	Front            string  `json:"front"`
	FrontImageBase64 *string `json:"front_image_base64,omitempty"`
	FrontImageType   *string `json:"front_image_type,omitempty"`
}

// GradeResult defines model for GradeResult.
type GradeResult struct {
	Correct         bool    `json:"correct"`
	CorrectedAnswer *string `json:"corrected_answer,omitempty"`
	Feedback        string  `json:"feedback"`
}

// ImageUploadResponse defines model for ImageUploadResponse.
type ImageUploadResponse struct {
	Id  openapi_types.UUID `json:"id"`
	Url string             `json:"url"`
}

// KnownWord defines model for KnownWord.
type KnownWord struct {
	Back  string `json:"back"`
	Front string `json:"front"`
}

// LanguagePairResponse defines model for LanguagePairResponse.
type LanguagePairResponse struct {
	SourceLang string `json:"source_lang"`
	SourceName string `json:"source_name"`
	TargetLang string `json:"target_lang"`
	TargetName string `json:"target_name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	CardId         openapi_types.UUID `json:"card_id"`
	Grade          int                `json:"grade"`
	ResponseTimeMs *int               `json:"response_time_ms,omitempty"`
	ReviewedAt     *time.Time         `json:"reviewed_at,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// SyncAction defines model for SyncAction.
type SyncAction struct {
	CardId         openapi_types.UUID `json:"card_id"`
	Grade          int                `json:"grade"`
	ResponseTimeMs *int               `json:"response_time_ms,omitempty"`
	ReviewedAt     *time.Time         `json:"reviewed_at,omitempty"`
}

// SyncRequest defines model for SyncRequest.
type SyncRequest struct {
	Actions []SyncAction `json:"actions"`
}

// SyncResult defines model for SyncResult.
type SyncResult struct {
	Errors    *[]string `json:"errors,omitempty"`
	Processed int       `json:"processed"`
}

// UpdateCardRequest defines model for UpdateCardRequest.
type UpdateCardRequest struct {
	Back         string              `json:"back"`
	BackImageId  *openapi_types.UUID `json:"back_image_id,omitempty"`
	Front        string              `json:"front"`
	FrontImageId *openapi_types.UUID `json:"front_image_id,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"created_at"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
}

// Error defines model for Error.
type Error = ErrorResponse

// UploadImageMultipartBody defines parameters for UploadImage.
type UploadImageMultipartBody struct {
	Image openapi_types.File `json:"image"`
}

// GetDueCardsParams defines parameters for GetDueCards.
type GetDueCardsParams struct {
	DeckId *openapi_types.UUID `form:"deck_id,omitempty" json:"deck_id,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// UpdateCardJSONRequestBody defines body for UpdateCard for application/json ContentType.
type UpdateCardJSONRequestBody = UpdateCardRequest

// CreateDeckJSONRequestBody defines body for CreateDeck for application/json ContentType.
type CreateDeckJSONRequestBody = CreateDeckRequest

// CreateCardJSONRequestBody defines body for CreateCard for application/json ContentType.
type CreateCardJSONRequestBody = CreateCardRequest

// CompleteExerciseJSONRequestBody defines body for CompleteExercise for application/json ContentType.
type CompleteExerciseJSONRequestBody = ExerciseCompleteRequest

// GenerateExercisesJSONRequestBody defines body for GenerateExercises for application/json ContentType.
type GenerateExercisesJSONRequestBody = ExerciseGenerateRequest

// GradeExerciseJSONRequestBody defines body for GradeExercise for application/json ContentType.
type GradeExerciseJSONRequestBody = ExerciseGradeRequest

// GenerateCardsJSONRequestBody defines body for GenerateCards for application/json ContentType.
type GenerateCardsJSONRequestBody = GenerateRequest

// UploadImageMultipartRequestBody defines body for UploadImage for multipart/form-data ContentType.
type UploadImageMultipartRequestBody UploadImageMultipartBody

// SubmitReviewJSONRequestBody defines body for SubmitReview for application/json ContentType.
type SubmitReviewJSONRequestBody = ReviewRequest

// SyncJSONRequestBody defines body for Sync for application/json ContentType.
type SyncJSONRequestBody = SyncRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)

	// (DELETE /cards/{id})
	DeleteCard(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PUT /cards/{id})
	UpdateCard(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /decks)
	ListDecks(w http.ResponseWriter, r *http.Request)

	// (POST /decks)
	CreateDeck(w http.ResponseWriter, r *http.Request)

	// (GET /decks/{deckId}/cards)
	ListCards(w http.ResponseWriter, r *http.Request, deckId openapi_types.UUID)

	// (POST /decks/{deckId}/cards)
	CreateCard(w http.ResponseWriter, r *http.Request, deckId openapi_types.UUID)

	// (DELETE /decks/{id})
	DeleteDeck(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /exercises/complete)
	CompleteExercise(w http.ResponseWriter, r *http.Request)

	// (GET /exercises/due)
	GetDueExercises(w http.ResponseWriter, r *http.Request)

	// (POST /exercises/generate)
	GenerateExercises(w http.ResponseWriter, r *http.Request)

	// (POST /exercises/grade)
	GradeExercise(w http.ResponseWriter, r *http.Request)

	// (POST /generate)
	GenerateCards(w http.ResponseWriter, r *http.Request)

	// (POST /images)
	UploadImage(w http.ResponseWriter, r *http.Request)

	// (GET /images/{id})
	GetImage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List supported language pairs
	// (GET /language-pairs)
	ListLanguagePairs(w http.ResponseWriter, r *http.Request)

	// (POST /review)
	SubmitReview(w http.ResponseWriter, r *http.Request)

	// (GET /review/due)
	GetDueCards(w http.ResponseWriter, r *http.Request, params GetDueCardsParams)

	// (POST /sync)
	Sync(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /cards/{id})
func (_ Unimplemented) DeleteCard(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /cards/{id})
func (_ Unimplemented) UpdateCard(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /decks)
func (_ Unimplemented) ListDecks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /decks)
func (_ Unimplemented) CreateDeck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /decks/{deckId}/cards)
func (_ Unimplemented) ListCards(w http.ResponseWriter, r *http.Request, deckId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /decks/{deckId}/cards)
func (_ Unimplemented) CreateCard(w http.ResponseWriter, r *http.Request, deckId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /decks/{id})
func (_ Unimplemented) DeleteDeck(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /exercises/complete)
func (_ Unimplemented) CompleteExercise(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /exercises/due)
func (_ Unimplemented) GetDueExercises(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /exercises/generate)
func (_ Unimplemented) GenerateExercises(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /exercises/grade)
func (_ Unimplemented) GradeExercise(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /generate)
func (_ Unimplemented) GenerateCards(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /images)
func (_ Unimplemented) UploadImage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /images/{id})
func (_ Unimplemented) GetImage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List supported language pairs
// (GET /language-pairs)
func (_ Unimplemented) ListLanguagePairs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /review)
func (_ Unimplemented) SubmitReview(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /review/due)
func (_ Unimplemented) GetDueCards(w http.ResponseWriter, r *http.Request, params GetDueCardsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /sync)
func (_ Unimplemented) Sync(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCard operation middleware
func (siw *ServerInterfaceWrapper) DeleteCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCard operation middleware
func (siw *ServerInterfaceWrapper) UpdateCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDecks operation middleware
func (siw *ServerInterfaceWrapper) ListDecks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDecks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeck operation middleware
func (siw *ServerInterfaceWrapper) CreateDeck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCards operation middleware
func (siw *ServerInterfaceWrapper) ListCards(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "deckId" -------------
	var deckId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deckId", chi.URLParam(r, "deckId"), &deckId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deckId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCards(w, r, deckId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCard operation middleware
func (siw *ServerInterfaceWrapper) CreateCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "deckId" -------------
	var deckId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deckId", chi.URLParam(r, "deckId"), &deckId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deckId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCard(w, r, deckId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDeck operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeck(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDeck(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteExercise operation middleware
func (siw *ServerInterfaceWrapper) CompleteExercise(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteExercise(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDueExercises operation middleware
func (siw *ServerInterfaceWrapper) GetDueExercises(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDueExercises(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateExercises operation middleware
func (siw *ServerInterfaceWrapper) GenerateExercises(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateExercises(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GradeExercise operation middleware
func (siw *ServerInterfaceWrapper) GradeExercise(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GradeExercise(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateCards operation middleware
func (siw *ServerInterfaceWrapper) GenerateCards(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateCards(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadImage operation middleware
func (siw *ServerInterfaceWrapper) UploadImage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadImage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLanguagePairs operation middleware
func (siw *ServerInterfaceWrapper) ListLanguagePairs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLanguagePairs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitReview operation middleware
func (siw *ServerInterfaceWrapper) SubmitReview(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitReview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDueCards operation middleware
func (siw *ServerInterfaceWrapper) GetDueCards(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDueCardsParams

	// ------------- Optional query parameter "deck_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deck_id", r.URL.Query(), &params.DeckId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deck_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDueCards(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Sync operation middleware
func (siw *ServerInterfaceWrapper) Sync(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Sync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cards/{id}", wrapper.DeleteCard)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/cards/{id}", wrapper.UpdateCard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/decks", wrapper.ListDecks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/decks", wrapper.CreateDeck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/decks/{deckId}/cards", wrapper.ListCards)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/decks/{deckId}/cards", wrapper.CreateCard)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/decks/{id}", wrapper.DeleteDeck)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/exercises/complete", wrapper.CompleteExercise)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/exercises/due", wrapper.GetDueExercises)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/exercises/generate", wrapper.GenerateExercises)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/exercises/grade", wrapper.GradeExercise)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generate", wrapper.GenerateCards)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/images", wrapper.UploadImage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/images/{id}", wrapper.GetImage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/language-pairs", wrapper.ListLanguagePairs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/review", wrapper.SubmitReview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/review/due", wrapper.GetDueCards)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sync", wrapper.Sync)
	})

	return r
}

type ErrorJSONResponse ErrorResponse

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LogindefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response LogindefaultJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RegisterdefaultJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteCardRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteCardResponseObject interface {
	VisitDeleteCardResponse(w http.ResponseWriter) error
}

type DeleteCard200JSONResponse StatusResponse

func (response DeleteCard200JSONResponse) VisitDeleteCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCarddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DeleteCarddefaultJSONResponse) VisitDeleteCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateCardRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateCardJSONRequestBody
}

type UpdateCardResponseObject interface {
	VisitUpdateCardResponse(w http.ResponseWriter) error
}

type UpdateCard200JSONResponse StatusResponse

func (response UpdateCard200JSONResponse) VisitUpdateCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCarddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response UpdateCarddefaultJSONResponse) VisitUpdateCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListDecksRequestObject struct {
}

type ListDecksResponseObject interface {
	VisitListDecksResponse(w http.ResponseWriter) error
}

type ListDecks200JSONResponse []Deck

func (response ListDecks200JSONResponse) VisitListDecksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDecksdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListDecksdefaultJSONResponse) VisitListDecksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateDeckRequestObject struct {
	Body *CreateDeckJSONRequestBody
}

type CreateDeckResponseObject interface {
	VisitCreateDeckResponse(w http.ResponseWriter) error
}

type CreateDeck201JSONResponse Deck

func (response CreateDeck201JSONResponse) VisitCreateDeckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeckdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CreateDeckdefaultJSONResponse) VisitCreateDeckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListCardsRequestObject struct {
	DeckId openapi_types.UUID `json:"deckId"`
}

type ListCardsResponseObject interface {
	VisitListCardsResponse(w http.ResponseWriter) error
}

type ListCards200JSONResponse []Card

func (response ListCards200JSONResponse) VisitListCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCardsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListCardsdefaultJSONResponse) VisitListCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateCardRequestObject struct {
	DeckId openapi_types.UUID `json:"deckId"`
	Body   *CreateCardJSONRequestBody
}

type CreateCardResponseObject interface {
	VisitCreateCardResponse(w http.ResponseWriter) error
}

type CreateCard201JSONResponse Card

func (response CreateCard201JSONResponse) VisitCreateCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateCarddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CreateCarddefaultJSONResponse) VisitCreateCardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteDeckRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteDeckResponseObject interface {
	VisitDeleteDeckResponse(w http.ResponseWriter) error
}

type DeleteDeck200JSONResponse StatusResponse

func (response DeleteDeck200JSONResponse) VisitDeleteDeckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDeckdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DeleteDeckdefaultJSONResponse) VisitDeleteDeckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CompleteExerciseRequestObject struct {
	Body *CompleteExerciseJSONRequestBody
}

type CompleteExerciseResponseObject interface {
	VisitCompleteExerciseResponse(w http.ResponseWriter) error
}

type CompleteExercise200JSONResponse StatusResponse

func (response CompleteExercise200JSONResponse) VisitCompleteExerciseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CompleteExercisedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CompleteExercisedefaultJSONResponse) VisitCompleteExerciseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetDueExercisesRequestObject struct {
}

type GetDueExercisesResponseObject interface {
	VisitGetDueExercisesResponse(w http.ResponseWriter) error
}

type GetDueExercises200JSONResponse []ExerciseResponse

func (response GetDueExercises200JSONResponse) VisitGetDueExercisesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDueExercisesdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetDueExercisesdefaultJSONResponse) VisitGetDueExercisesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GenerateExercisesRequestObject struct {
	Body *GenerateExercisesJSONRequestBody
}

type GenerateExercisesResponseObject interface {
	VisitGenerateExercisesResponse(w http.ResponseWriter) error
}

type GenerateExercises200JSONResponse []ExerciseResponse

func (response GenerateExercises200JSONResponse) VisitGenerateExercisesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateExercisesdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GenerateExercisesdefaultJSONResponse) VisitGenerateExercisesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GradeExerciseRequestObject struct {
	Body *GradeExerciseJSONRequestBody
}

type GradeExerciseResponseObject interface {
	VisitGradeExerciseResponse(w http.ResponseWriter) error
}

type GradeExercise200JSONResponse GradeResult

func (response GradeExercise200JSONResponse) VisitGradeExerciseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GradeExercisedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GradeExercisedefaultJSONResponse) VisitGradeExerciseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GenerateCardsRequestObject struct {
	Body *GenerateCardsJSONRequestBody
}

type GenerateCardsResponseObject interface {
	VisitGenerateCardsResponse(w http.ResponseWriter) error
}

type GenerateCards200JSONResponse []GeneratedCard

func (response GenerateCards200JSONResponse) VisitGenerateCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateCardsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GenerateCardsdefaultJSONResponse) VisitGenerateCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UploadImageRequestObject struct {
	Body *multipart.Reader
}

type UploadImageResponseObject interface {
	VisitUploadImageResponse(w http.ResponseWriter) error
}

type UploadImage201JSONResponse ImageUploadResponse

func (response UploadImage201JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type UploadImagedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response UploadImagedefaultJSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetImageRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200ImageResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response GetImage200ImageResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImagedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetImagedefaultJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListLanguagePairsRequestObject struct {
}

type ListLanguagePairsResponseObject interface {
	VisitListLanguagePairsResponse(w http.ResponseWriter) error
}

type ListLanguagePairs200JSONResponse []LanguagePairResponse

func (response ListLanguagePairs200JSONResponse) VisitListLanguagePairsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SubmitReviewRequestObject struct {
	Body *SubmitReviewJSONRequestBody
}

type SubmitReviewResponseObject interface {
	VisitSubmitReviewResponse(w http.ResponseWriter) error
}

type SubmitReview200JSONResponse Card

func (response SubmitReview200JSONResponse) VisitSubmitReviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SubmitReviewdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response SubmitReviewdefaultJSONResponse) VisitSubmitReviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetDueCardsRequestObject struct {
	Params GetDueCardsParams
}

type GetDueCardsResponseObject interface {
	VisitGetDueCardsResponse(w http.ResponseWriter) error
}

type GetDueCards200JSONResponse []Card

func (response GetDueCards200JSONResponse) VisitGetDueCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDueCardsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetDueCardsdefaultJSONResponse) VisitGetDueCardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SyncRequestObject struct {
	Body *SyncJSONRequestBody
}

type SyncResponseObject interface {
	VisitSyncResponse(w http.ResponseWriter) error
}

type Sync200JSONResponse SyncResult

func (response Sync200JSONResponse) VisitSyncResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SyncdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response SyncdefaultJSONResponse) VisitSyncResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)

	// (DELETE /cards/{id})
	DeleteCard(ctx context.Context, request DeleteCardRequestObject) (DeleteCardResponseObject, error)

	// (PUT /cards/{id})
	UpdateCard(ctx context.Context, request UpdateCardRequestObject) (UpdateCardResponseObject, error)

	// (GET /decks)
	ListDecks(ctx context.Context, request ListDecksRequestObject) (ListDecksResponseObject, error)

	// (POST /decks)
	CreateDeck(ctx context.Context, request CreateDeckRequestObject) (CreateDeckResponseObject, error)

	// (GET /decks/{deckId}/cards)
	ListCards(ctx context.Context, request ListCardsRequestObject) (ListCardsResponseObject, error)

	// (POST /decks/{deckId}/cards)
	CreateCard(ctx context.Context, request CreateCardRequestObject) (CreateCardResponseObject, error)

	// (DELETE /decks/{id})
	DeleteDeck(ctx context.Context, request DeleteDeckRequestObject) (DeleteDeckResponseObject, error)

	// (POST /exercises/complete)
	CompleteExercise(ctx context.Context, request CompleteExerciseRequestObject) (CompleteExerciseResponseObject, error)

	// (GET /exercises/due)
	GetDueExercises(ctx context.Context, request GetDueExercisesRequestObject) (GetDueExercisesResponseObject, error)

	// (POST /exercises/generate)
	GenerateExercises(ctx context.Context, request GenerateExercisesRequestObject) (GenerateExercisesResponseObject, error)

	// (POST /exercises/grade)
	GradeExercise(ctx context.Context, request GradeExerciseRequestObject) (GradeExerciseResponseObject, error)

	// (POST /generate)
	GenerateCards(ctx context.Context, request GenerateCardsRequestObject) (GenerateCardsResponseObject, error)

	// (POST /images)
	UploadImage(ctx context.Context, request UploadImageRequestObject) (UploadImageResponseObject, error)

	// (GET /images/{id})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
	// List supported language pairs
	// (GET /language-pairs)
	ListLanguagePairs(ctx context.Context, request ListLanguagePairsRequestObject) (ListLanguagePairsResponseObject, error)

	// (POST /review)
	SubmitReview(ctx context.Context, request SubmitReviewRequestObject) (SubmitReviewResponseObject, error)

	// (GET /review/due)
	GetDueCards(ctx context.Context, request GetDueCardsRequestObject) (GetDueCardsResponseObject, error)

	// (POST /sync)
	Sync(ctx context.Context, request SyncRequestObject) (SyncResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCard operation middleware
func (sh *strictHandler) DeleteCard(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteCardRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCard(ctx, request.(DeleteCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCardResponseObject); ok {
		if err := validResponse.VisitDeleteCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCard operation middleware
func (sh *strictHandler) UpdateCard(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateCardRequestObject

	request.Id = id

	var body UpdateCardJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCard(ctx, request.(UpdateCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCardResponseObject); ok {
		if err := validResponse.VisitUpdateCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDecks operation middleware
func (sh *strictHandler) ListDecks(w http.ResponseWriter, r *http.Request) {
	var request ListDecksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDecks(ctx, request.(ListDecksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDecks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDecksResponseObject); ok {
		if err := validResponse.VisitListDecksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDeck operation middleware
func (sh *strictHandler) CreateDeck(w http.ResponseWriter, r *http.Request) {
	var request CreateDeckRequestObject

	var body CreateDeckJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDeck(ctx, request.(CreateDeckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDeck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeckResponseObject); ok {
		if err := validResponse.VisitCreateDeckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCards operation middleware
func (sh *strictHandler) ListCards(w http.ResponseWriter, r *http.Request, deckId openapi_types.UUID) {
	var request ListCardsRequestObject

	request.DeckId = deckId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCards(ctx, request.(ListCardsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCards")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCardsResponseObject); ok {
		if err := validResponse.VisitListCardsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCard operation middleware
func (sh *strictHandler) CreateCard(w http.ResponseWriter, r *http.Request, deckId openapi_types.UUID) {
	var request CreateCardRequestObject

	request.DeckId = deckId

	var body CreateCardJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCard(ctx, request.(CreateCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCardResponseObject); ok {
		if err := validResponse.VisitCreateCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDeck operation middleware
func (sh *strictHandler) DeleteDeck(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteDeckRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDeck(ctx, request.(DeleteDeckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDeck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeckResponseObject); ok {
		if err := validResponse.VisitDeleteDeckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteExercise operation middleware
func (sh *strictHandler) CompleteExercise(w http.ResponseWriter, r *http.Request) {
	var request CompleteExerciseRequestObject

	var body CompleteExerciseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteExercise(ctx, request.(CompleteExerciseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteExercise")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteExerciseResponseObject); ok {
		if err := validResponse.VisitCompleteExerciseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDueExercises operation middleware
func (sh *strictHandler) GetDueExercises(w http.ResponseWriter, r *http.Request) {
	var request GetDueExercisesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDueExercises(ctx, request.(GetDueExercisesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDueExercises")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDueExercisesResponseObject); ok {
		if err := validResponse.VisitGetDueExercisesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateExercises operation middleware
func (sh *strictHandler) GenerateExercises(w http.ResponseWriter, r *http.Request) {
	var request GenerateExercisesRequestObject

	var body GenerateExercisesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateExercises(ctx, request.(GenerateExercisesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateExercises")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateExercisesResponseObject); ok {
		if err := validResponse.VisitGenerateExercisesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GradeExercise operation middleware
func (sh *strictHandler) GradeExercise(w http.ResponseWriter, r *http.Request) {
	var request GradeExerciseRequestObject

	var body GradeExerciseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GradeExercise(ctx, request.(GradeExerciseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GradeExercise")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GradeExerciseResponseObject); ok {
		if err := validResponse.VisitGradeExerciseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateCards operation middleware
func (sh *strictHandler) GenerateCards(w http.ResponseWriter, r *http.Request) {
	var request GenerateCardsRequestObject

	var body GenerateCardsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateCards(ctx, request.(GenerateCardsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateCards")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateCardsResponseObject); ok {
		if err := validResponse.VisitGenerateCardsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadImage operation middleware
func (sh *strictHandler) UploadImage(w http.ResponseWriter, r *http.Request) {
	var request UploadImageRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadImage(ctx, request.(UploadImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadImage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadImageResponseObject); ok {
		if err := validResponse.VisitUploadImageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetImageRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx, request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		if err := validResponse.VisitGetImageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLanguagePairs operation middleware
func (sh *strictHandler) ListLanguagePairs(w http.ResponseWriter, r *http.Request) {
	var request ListLanguagePairsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLanguagePairs(ctx, request.(ListLanguagePairsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLanguagePairs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLanguagePairsResponseObject); ok {
		if err := validResponse.VisitListLanguagePairsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitReview operation middleware
func (sh *strictHandler) SubmitReview(w http.ResponseWriter, r *http.Request) {
	var request SubmitReviewRequestObject

	var body SubmitReviewJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitReview(ctx, request.(SubmitReviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitReview")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitReviewResponseObject); ok {
		if err := validResponse.VisitSubmitReviewResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDueCards operation middleware
func (sh *strictHandler) GetDueCards(w http.ResponseWriter, r *http.Request, params GetDueCardsParams) {
	var request GetDueCardsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDueCards(ctx, request.(GetDueCardsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDueCards")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDueCardsResponseObject); ok {
		if err := validResponse.VisitGetDueCardsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Sync operation middleware
func (sh *strictHandler) Sync(w http.ResponseWriter, r *http.Request) {
	var request SyncRequestObject

	var body SyncJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Sync(ctx, request.(SyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Sync")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SyncResponseObject); ok {
		if err := validResponse.VisitSyncResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
