/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Card,
  CreateCardRequest,
  ErrorResponse,
  StatusResponse,
  UpdateCardRequest,
} from '../models/index';
import {
    CardFromJSON,
    CardToJSON,
    CreateCardRequestFromJSON,
    CreateCardRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    StatusResponseFromJSON,
    StatusResponseToJSON,
    UpdateCardRequestFromJSON,
    UpdateCardRequestToJSON,
} from '../models/index';

export interface CreateCardOperationRequest {
    deckId: string;
    CreateCardRequest: CreateCardRequest;
}

export interface DeleteCardRequest {
    id: string;
}

export interface ListCardsRequest {
    deckId: string;
}

export interface UpdateCardOperationRequest {
    id: string;
    UpdateCardRequest: UpdateCardRequest;
}

/**
 * 
 */
export class CardsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCard without sending the request
     */
    async createCardRequestOpts(requestParameters: CreateCardOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deckId'] == null) {
            throw new runtime.RequiredError(
                'deckId',
                'Required parameter "deckId" was null or undefined when calling createCard().'
            );
        }

        if (requestParameters['CreateCardRequest'] == null) {
            throw new runtime.RequiredError(
                'CreateCardRequest',
                'Required parameter "CreateCardRequest" was null or undefined when calling createCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/decks/{deckId}/cards`;
        urlPath = urlPath.replace(`{${"deckId"}}`, encodeURIComponent(String(requestParameters['deckId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCardRequestToJSON(requestParameters['CreateCardRequest']),
        };
    }

    /**
     */
    async createCardRaw(requestParameters: CreateCardOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Card>> {
        const requestOptions = await this.createCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardFromJSON(jsonValue));
    }

    /**
     */
    async createCard(requestParameters: CreateCardOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Card> {
        const response = await this.createCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCard without sending the request
     */
    async deleteCardRequestOpts(requestParameters: DeleteCardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/cards/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteCardRaw(requestParameters: DeleteCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>> {
        const requestOptions = await this.deleteCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusResponseFromJSON(jsonValue));
    }

    /**
     */
    async deleteCard(requestParameters: DeleteCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse> {
        const response = await this.deleteCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCards without sending the request
     */
    async listCardsRequestOpts(requestParameters: ListCardsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deckId'] == null) {
            throw new runtime.RequiredError(
                'deckId',
                'Required parameter "deckId" was null or undefined when calling listCards().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/decks/{deckId}/cards`;
        urlPath = urlPath.replace(`{${"deckId"}}`, encodeURIComponent(String(requestParameters['deckId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listCardsRaw(requestParameters: ListCardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Card>>> {
        const requestOptions = await this.listCardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CardFromJSON));
    }

    /**
     */
    async listCards(requestParameters: ListCardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Card>> {
        const response = await this.listCardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCard without sending the request
     */
    async updateCardRequestOpts(requestParameters: UpdateCardOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCard().'
            );
        }

        if (requestParameters['UpdateCardRequest'] == null) {
            throw new runtime.RequiredError(
                'UpdateCardRequest',
                'Required parameter "UpdateCardRequest" was null or undefined when calling updateCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/cards/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCardRequestToJSON(requestParameters['UpdateCardRequest']),
        };
    }

    /**
     */
    async updateCardRaw(requestParameters: UpdateCardOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>> {
        const requestOptions = await this.updateCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateCard(requestParameters: UpdateCardOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse> {
        const response = await this.updateCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
