/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  CreateDeckRequest,
  Deck,
  ErrorResponse,
  StatusResponse,
} from "../models/index";
import {
  CreateDeckRequestFromJSON,
  CreateDeckRequestToJSON,
  DeckFromJSON,
  DeckToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  StatusResponseFromJSON,
  StatusResponseToJSON,
} from "../models/index";

export interface CreateDeckOperationRequest {
  CreateDeckRequest: CreateDeckRequest;
}

export interface DeleteDeckRequest {
  id: string;
}

/**
 *
 */
export class DecksApi extends runtime.BaseAPI {
  /**
   * Creates request options for createDeck without sending the request
   */
  async createDeckRequestOpts(
    requestParameters: CreateDeckOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["CreateDeckRequest"] == null) {
      throw new runtime.RequiredError(
        "CreateDeckRequest",
        'Required parameter "CreateDeckRequest" was null or undefined when calling createDeck().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/decks`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreateDeckRequestToJSON(requestParameters["CreateDeckRequest"]),
    };
  }

  /**
   */
  async createDeckRaw(
    requestParameters: CreateDeckOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Deck>> {
    const requestOptions = await this.createDeckRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeckFromJSON(jsonValue),
    );
  }

  /**
   */
  async createDeck(
    requestParameters: CreateDeckOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Deck> {
    const response = await this.createDeckRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteDeck without sending the request
   */
  async deleteDeckRequestOpts(
    requestParameters: DeleteDeckRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling deleteDeck().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/decks/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   */
  async deleteDeckRaw(
    requestParameters: DeleteDeckRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StatusResponse>> {
    const requestOptions = await this.deleteDeckRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StatusResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async deleteDeck(
    requestParameters: DeleteDeckRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StatusResponse> {
    const response = await this.deleteDeckRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listDecks without sending the request
   */
  async listDecksRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/decks`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   */
  async listDecksRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Deck>>> {
    const requestOptions = await this.listDecksRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DeckFromJSON),
    );
  }

  /**
   */
  async listDecks(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Deck>> {
    const response = await this.listDecksRaw(initOverrides);
    return await response.value();
  }
}
