/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  ErrorResponse,
  ExerciseCompleteRequest,
  ExerciseGenerateRequest,
  ExerciseGradeRequest,
  ExerciseResponse,
  GradeResult,
  StatusResponse,
} from "../models/index";
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  ExerciseCompleteRequestFromJSON,
  ExerciseCompleteRequestToJSON,
  ExerciseGenerateRequestFromJSON,
  ExerciseGenerateRequestToJSON,
  ExerciseGradeRequestFromJSON,
  ExerciseGradeRequestToJSON,
  ExerciseResponseFromJSON,
  ExerciseResponseToJSON,
  GradeResultFromJSON,
  GradeResultToJSON,
  StatusResponseFromJSON,
  StatusResponseToJSON,
} from "../models/index";

export interface CompleteExerciseRequest {
  ExerciseCompleteRequest: ExerciseCompleteRequest;
}

export interface GenerateExercisesRequest {
  ExerciseGenerateRequest: ExerciseGenerateRequest;
}

export interface GradeExerciseRequest {
  ExerciseGradeRequest: ExerciseGradeRequest;
}

/**
 *
 */
export class ExercisesApi extends runtime.BaseAPI {
  /**
   * Creates request options for completeExercise without sending the request
   */
  async completeExerciseRequestOpts(
    requestParameters: CompleteExerciseRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["ExerciseCompleteRequest"] == null) {
      throw new runtime.RequiredError(
        "ExerciseCompleteRequest",
        'Required parameter "ExerciseCompleteRequest" was null or undefined when calling completeExercise().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/exercises/complete`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: ExerciseCompleteRequestToJSON(
        requestParameters["ExerciseCompleteRequest"],
      ),
    };
  }

  /**
   */
  async completeExerciseRaw(
    requestParameters: CompleteExerciseRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StatusResponse>> {
    const requestOptions =
      await this.completeExerciseRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StatusResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async completeExercise(
    requestParameters: CompleteExerciseRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StatusResponse> {
    const response = await this.completeExerciseRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for generateExercises without sending the request
   */
  async generateExercisesRequestOpts(
    requestParameters: GenerateExercisesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["ExerciseGenerateRequest"] == null) {
      throw new runtime.RequiredError(
        "ExerciseGenerateRequest",
        'Required parameter "ExerciseGenerateRequest" was null or undefined when calling generateExercises().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/exercises/generate`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: ExerciseGenerateRequestToJSON(
        requestParameters["ExerciseGenerateRequest"],
      ),
    };
  }

  /**
   */
  async generateExercisesRaw(
    requestParameters: GenerateExercisesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ExerciseResponse>>> {
    const requestOptions =
      await this.generateExercisesRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ExerciseResponseFromJSON),
    );
  }

  /**
   */
  async generateExercises(
    requestParameters: GenerateExercisesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ExerciseResponse>> {
    const response = await this.generateExercisesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for getDueExercises without sending the request
   */
  async getDueExercisesRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/exercises/due`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   */
  async getDueExercisesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ExerciseResponse>>> {
    const requestOptions = await this.getDueExercisesRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ExerciseResponseFromJSON),
    );
  }

  /**
   */
  async getDueExercises(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ExerciseResponse>> {
    const response = await this.getDueExercisesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for gradeExercise without sending the request
   */
  async gradeExerciseRequestOpts(
    requestParameters: GradeExerciseRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["ExerciseGradeRequest"] == null) {
      throw new runtime.RequiredError(
        "ExerciseGradeRequest",
        'Required parameter "ExerciseGradeRequest" was null or undefined when calling gradeExercise().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/exercises/grade`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: ExerciseGradeRequestToJSON(
        requestParameters["ExerciseGradeRequest"],
      ),
    };
  }

  /**
   */
  async gradeExerciseRaw(
    requestParameters: GradeExerciseRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GradeResult>> {
    const requestOptions =
      await this.gradeExerciseRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GradeResultFromJSON(jsonValue),
    );
  }

  /**
   */
  async gradeExercise(
    requestParameters: GradeExerciseRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GradeResult> {
    const response = await this.gradeExerciseRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
