/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GenerateRequest,
  GeneratedCard,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GenerateRequestFromJSON,
    GenerateRequestToJSON,
    GeneratedCardFromJSON,
    GeneratedCardToJSON,
} from '../models/index';

export interface GenerateCardsRequest {
    GenerateRequest: GenerateRequest;
}

/**
 * 
 */
export class GenerateApi extends runtime.BaseAPI {

    /**
     * Creates request options for generateCards without sending the request
     */
    async generateCardsRequestOpts(requestParameters: GenerateCardsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['GenerateRequest'] == null) {
            throw new runtime.RequiredError(
                'GenerateRequest',
                'Required parameter "GenerateRequest" was null or undefined when calling generateCards().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/generate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateRequestToJSON(requestParameters['GenerateRequest']),
        };
    }

    /**
     */
    async generateCardsRaw(requestParameters: GenerateCardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GeneratedCard>>> {
        const requestOptions = await this.generateCardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GeneratedCardFromJSON));
    }

    /**
     */
    async generateCards(requestParameters: GenerateCardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GeneratedCard>> {
        const response = await this.generateCardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
