/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LanguagePairResponse,
} from '../models/index';
import {
    LanguagePairResponseFromJSON,
    LanguagePairResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class LanguagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for listLanguagePairs without sending the request
     */
    async listLanguagePairsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/language-pairs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List supported language pairs
     */
    async listLanguagePairsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LanguagePairResponse>>> {
        const requestOptions = await this.listLanguagePairsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LanguagePairResponseFromJSON));
    }

    /**
     * List supported language pairs
     */
    async listLanguagePairs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LanguagePairResponse>> {
        const response = await this.listLanguagePairsRaw(initOverrides);
        return await response.value();
    }

}
