/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { Card, ErrorResponse, ReviewRequest } from "../models/index";
import {
  CardFromJSON,
  CardToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  ReviewRequestFromJSON,
  ReviewRequestToJSON,
} from "../models/index";

export interface GetDueCardsRequest {
  deck_id?: string;
}

export interface SubmitReviewRequest {
  ReviewRequest: ReviewRequest;
}

/**
 *
 */
export class ReviewApi extends runtime.BaseAPI {
  /**
   * Creates request options for getDueCards without sending the request
   */
  async getDueCardsRequestOpts(
    requestParameters: GetDueCardsRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["deck_id"] != null) {
      queryParameters["deck_id"] = requestParameters["deck_id"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/review/due`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   */
  async getDueCardsRaw(
    requestParameters: GetDueCardsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Card>>> {
    const requestOptions = await this.getDueCardsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(CardFromJSON),
    );
  }

  /**
   */
  async getDueCards(
    requestParameters: GetDueCardsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Card>> {
    const response = await this.getDueCardsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for submitReview without sending the request
   */
  async submitReviewRequestOpts(
    requestParameters: SubmitReviewRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["ReviewRequest"] == null) {
      throw new runtime.RequiredError(
        "ReviewRequest",
        'Required parameter "ReviewRequest" was null or undefined when calling submitReview().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/review`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: ReviewRequestToJSON(requestParameters["ReviewRequest"]),
    };
  }

  /**
   */
  async submitReviewRaw(
    requestParameters: SubmitReviewRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Card>> {
    const requestOptions =
      await this.submitReviewRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CardFromJSON(jsonValue),
    );
  }

  /**
   */
  async submitReview(
    requestParameters: SubmitReviewRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Card> {
    const response = await this.submitReviewRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
