/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ErrorResponse, SyncRequest, SyncResult } from "../models/index";
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  SyncRequestFromJSON,
  SyncRequestToJSON,
  SyncResultFromJSON,
  SyncResultToJSON,
} from "../models/index";

export interface SyncOperationRequest {
  SyncRequest: SyncRequest;
}

/**
 *
 */
export class SyncApi extends runtime.BaseAPI {
  /**
   * Creates request options for sync without sending the request
   */
  async syncRequestOpts(
    requestParameters: SyncOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["SyncRequest"] == null) {
      throw new runtime.RequiredError(
        "SyncRequest",
        'Required parameter "SyncRequest" was null or undefined when calling sync().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/sync`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: SyncRequestToJSON(requestParameters["SyncRequest"]),
    };
  }

  /**
   */
  async syncRaw(
    requestParameters: SyncOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SyncResult>> {
    const requestOptions = await this.syncRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SyncResultFromJSON(jsonValue),
    );
  }

  /**
   */
  async sync(
    requestParameters: SyncOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SyncResult> {
    const response = await this.syncRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
