/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Card
 */
export interface Card {
  /**
   *
   * @type {string}
   * @memberof Card
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Card
   */
  deck_id: string;
  /**
   *
   * @type {string}
   * @memberof Card
   */
  front: string;
  /**
   *
   * @type {string}
   * @memberof Card
   */
  back: string;
  /**
   *
   * @type {string}
   * @memberof Card
   */
  front_image_url?: string;
  /**
   *
   * @type {string}
   * @memberof Card
   */
  back_image_url?: string;
  /**
   *
   * @type {number}
   * @memberof Card
   */
  ease_factor: number;
  /**
   *
   * @type {number}
   * @memberof Card
   */
  interval_days: number;
  /**
   *
   * @type {number}
   * @memberof Card
   */
  repetitions: number;
  /**
   *
   * @type {Date}
   * @memberof Card
   */
  next_review: Date;
  /**
   *
   * @type {Date}
   * @memberof Card
   */
  created_at: Date;
  /**
   *
   * @type {Date}
   * @memberof Card
   */
  updated_at: Date;
}

/**
 * Check if a given object implements the Card interface.
 */
export function instanceOfCard(value: object): value is Card {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("deck_id" in value) || value["deck_id"] === undefined) return false;
  if (!("front" in value) || value["front"] === undefined) return false;
  if (!("back" in value) || value["back"] === undefined) return false;
  if (!("ease_factor" in value) || value["ease_factor"] === undefined)
    return false;
  if (!("interval_days" in value) || value["interval_days"] === undefined)
    return false;
  if (!("repetitions" in value) || value["repetitions"] === undefined)
    return false;
  if (!("next_review" in value) || value["next_review"] === undefined)
    return false;
  if (!("created_at" in value) || value["created_at"] === undefined)
    return false;
  if (!("updated_at" in value) || value["updated_at"] === undefined)
    return false;
  return true;
}

export function CardFromJSON(json: any): Card {
  return CardFromJSONTyped(json, false);
}

export function CardFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Card {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    deck_id: json["deck_id"],
    front: json["front"],
    back: json["back"],
    front_image_url:
      json["front_image_url"] == null ? undefined : json["front_image_url"],
    back_image_url:
      json["back_image_url"] == null ? undefined : json["back_image_url"],
    ease_factor: json["ease_factor"],
    interval_days: json["interval_days"],
    repetitions: json["repetitions"],
    next_review: new Date(json["next_review"]),
    created_at: new Date(json["created_at"]),
    updated_at: new Date(json["updated_at"]),
  };
}

export function CardToJSON(json: any): Card {
  return CardToJSONTyped(json, false);
}

export function CardToJSONTyped(
  value?: Card | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    deck_id: value["deck_id"],
    front: value["front"],
    back: value["back"],
    front_image_url: value["front_image_url"],
    back_image_url: value["back_image_url"],
    ease_factor: value["ease_factor"],
    interval_days: value["interval_days"],
    repetitions: value["repetitions"],
    next_review: value["next_review"].toISOString(),
    created_at: value["created_at"].toISOString(),
    updated_at: value["updated_at"].toISOString(),
  };
}
