/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateDeckRequest
 */
export interface CreateDeckRequest {
  /**
   *
   * @type {string}
   * @memberof CreateDeckRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateDeckRequest
   */
  source_lang: string;
  /**
   *
   * @type {string}
   * @memberof CreateDeckRequest
   */
  target_lang: string;
}

/**
 * Check if a given object implements the CreateDeckRequest interface.
 */
export function instanceOfCreateDeckRequest(
  value: object,
): value is CreateDeckRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("source_lang" in value) || value["source_lang"] === undefined)
    return false;
  if (!("target_lang" in value) || value["target_lang"] === undefined)
    return false;
  return true;
}

export function CreateDeckRequestFromJSON(json: any): CreateDeckRequest {
  return CreateDeckRequestFromJSONTyped(json, false);
}

export function CreateDeckRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateDeckRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    source_lang: json["source_lang"],
    target_lang: json["target_lang"],
  };
}

export function CreateDeckRequestToJSON(json: any): CreateDeckRequest {
  return CreateDeckRequestToJSONTyped(json, false);
}

export function CreateDeckRequestToJSONTyped(
  value?: CreateDeckRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    source_lang: value["source_lang"],
    target_lang: value["target_lang"],
  };
}
