/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCardRequest
 */
export interface CreateCardRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequest
     */
    front: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequest
     */
    back: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequest
     */
    front_image_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequest
     */
    back_image_id?: string;
}

/**
 * Check if a given object implements the CreateCardRequest interface.
 */
export function instanceOfCreateCardRequest(value: object): value is CreateCardRequest {
    if (!('front' in value) || value['front'] === undefined) return false;
    if (!('back' in value) || value['back'] === undefined) return false;
    return true;
}

export function CreateCardRequestFromJSON(json: any): CreateCardRequest {
    return CreateCardRequestFromJSONTyped(json, false);
}

export function CreateCardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'front': json['front'],
        'back': json['back'],
        'front_image_id': json['front_image_id'] == null ? undefined : json['front_image_id'],
        'back_image_id': json['back_image_id'] == null ? undefined : json['back_image_id'],
    };
}

export function CreateCardRequestToJSON(json: any): CreateCardRequest {
    return CreateCardRequestToJSONTyped(json, false);
}

export function CreateCardRequestToJSONTyped(value?: CreateCardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front': value['front'],
        'back': value['back'],
        'front_image_id': value['front_image_id'],
        'back_image_id': value['back_image_id'],
    };
}

