/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Deck
 */
export interface Deck {
  /**
   *
   * @type {string}
   * @memberof Deck
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Deck
   */
  user_id: string;
  /**
   *
   * @type {string}
   * @memberof Deck
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Deck
   */
  source_lang: string;
  /**
   *
   * @type {string}
   * @memberof Deck
   */
  target_lang: string;
  /**
   *
   * @type {Date}
   * @memberof Deck
   */
  created_at: Date;
}

/**
 * Check if a given object implements the Deck interface.
 */
export function instanceOfDeck(value: object): value is Deck {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("user_id" in value) || value["user_id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("source_lang" in value) || value["source_lang"] === undefined)
    return false;
  if (!("target_lang" in value) || value["target_lang"] === undefined)
    return false;
  if (!("created_at" in value) || value["created_at"] === undefined)
    return false;
  return true;
}

export function DeckFromJSON(json: any): Deck {
  return DeckFromJSONTyped(json, false);
}

export function DeckFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Deck {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    user_id: json["user_id"],
    name: json["name"],
    source_lang: json["source_lang"],
    target_lang: json["target_lang"],
    created_at: new Date(json["created_at"]),
  };
}

export function DeckToJSON(json: any): Deck {
  return DeckToJSONTyped(json, false);
}

export function DeckToJSONTyped(
  value?: Deck | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    user_id: value["user_id"],
    name: value["name"],
    source_lang: value["source_lang"],
    target_lang: value["target_lang"],
    created_at: value["created_at"].toISOString(),
  };
}
