/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseCompleteRequest
 */
export interface ExerciseCompleteRequest {
    /**
     * 
     * @type {string}
     * @memberof ExerciseCompleteRequest
     */
    exercise_id: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseCompleteRequest
     */
    user_answer: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExerciseCompleteRequest
     */
    correct: boolean;
}

/**
 * Check if a given object implements the ExerciseCompleteRequest interface.
 */
export function instanceOfExerciseCompleteRequest(value: object): value is ExerciseCompleteRequest {
    if (!('exercise_id' in value) || value['exercise_id'] === undefined) return false;
    if (!('user_answer' in value) || value['user_answer'] === undefined) return false;
    if (!('correct' in value) || value['correct'] === undefined) return false;
    return true;
}

export function ExerciseCompleteRequestFromJSON(json: any): ExerciseCompleteRequest {
    return ExerciseCompleteRequestFromJSONTyped(json, false);
}

export function ExerciseCompleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseCompleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exercise_id': json['exercise_id'],
        'user_answer': json['user_answer'],
        'correct': json['correct'],
    };
}

export function ExerciseCompleteRequestToJSON(json: any): ExerciseCompleteRequest {
    return ExerciseCompleteRequestToJSONTyped(json, false);
}

export function ExerciseCompleteRequestToJSONTyped(value?: ExerciseCompleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exercise_id': value['exercise_id'],
        'user_answer': value['user_answer'],
        'correct': value['correct'],
    };
}

