/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ExerciseGradeRequest
 */
export interface ExerciseGradeRequest {
  /**
   *
   * @type {string}
   * @memberof ExerciseGradeRequest
   */
  exercise_id?: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseGradeRequest
   */
  exercise_type?: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseGradeRequest
   */
  prompt?: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseGradeRequest
   */
  correct_answer: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseGradeRequest
   */
  user_answer: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseGradeRequest
   */
  source_lang: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseGradeRequest
   */
  target_lang: string;
}

/**
 * Check if a given object implements the ExerciseGradeRequest interface.
 */
export function instanceOfExerciseGradeRequest(
  value: object,
): value is ExerciseGradeRequest {
  if (!("correct_answer" in value) || value["correct_answer"] === undefined)
    return false;
  if (!("user_answer" in value) || value["user_answer"] === undefined)
    return false;
  if (!("source_lang" in value) || value["source_lang"] === undefined)
    return false;
  if (!("target_lang" in value) || value["target_lang"] === undefined)
    return false;
  return true;
}

export function ExerciseGradeRequestFromJSON(json: any): ExerciseGradeRequest {
  return ExerciseGradeRequestFromJSONTyped(json, false);
}

export function ExerciseGradeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExerciseGradeRequest {
  if (json == null) {
    return json;
  }
  return {
    exercise_id: json["exercise_id"] == null ? undefined : json["exercise_id"],
    exercise_type:
      json["exercise_type"] == null ? undefined : json["exercise_type"],
    prompt: json["prompt"] == null ? undefined : json["prompt"],
    correct_answer: json["correct_answer"],
    user_answer: json["user_answer"],
    source_lang: json["source_lang"],
    target_lang: json["target_lang"],
  };
}

export function ExerciseGradeRequestToJSON(json: any): ExerciseGradeRequest {
  return ExerciseGradeRequestToJSONTyped(json, false);
}

export function ExerciseGradeRequestToJSONTyped(
  value?: ExerciseGradeRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    exercise_id: value["exercise_id"],
    exercise_type: value["exercise_type"],
    prompt: value["prompt"],
    correct_answer: value["correct_answer"],
    user_answer: value["user_answer"],
    source_lang: value["source_lang"],
    target_lang: value["target_lang"],
  };
}
