/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ExerciseCard
 */
export interface ExerciseCard {
  /**
   *
   * @type {string}
   * @memberof ExerciseCard
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseCard
   */
  front: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseCard
   */
  back: string;
  /**
   *
   * @type {number}
   * @memberof ExerciseCard
   */
  level: number;
}

/**
 * Check if a given object implements the ExerciseCard interface.
 */
export function instanceOfExerciseCard(value: object): value is ExerciseCard {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("front" in value) || value["front"] === undefined) return false;
  if (!("back" in value) || value["back"] === undefined) return false;
  if (!("level" in value) || value["level"] === undefined) return false;
  return true;
}

export function ExerciseCardFromJSON(json: any): ExerciseCard {
  return ExerciseCardFromJSONTyped(json, false);
}

export function ExerciseCardFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExerciseCard {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    front: json["front"],
    back: json["back"],
    level: json["level"],
  };
}

export function ExerciseCardToJSON(json: any): ExerciseCard {
  return ExerciseCardToJSONTyped(json, false);
}

export function ExerciseCardToJSONTyped(
  value?: ExerciseCard | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    front: value["front"],
    back: value["back"],
    level: value["level"],
  };
}
