/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseResponse
 */
export interface ExerciseResponse {
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof ExerciseResponse
     */
    level: number;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    instruction: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    correct_answer: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    hint?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    source_sentence?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseResponse
     */
    options?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ExerciseResponse
     */
    data?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ExerciseResponse
     */
    source_card_id: string;
}

/**
 * Check if a given object implements the ExerciseResponse interface.
 */
export function instanceOfExerciseResponse(value: object): value is ExerciseResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('instruction' in value) || value['instruction'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('correct_answer' in value) || value['correct_answer'] === undefined) return false;
    if (!('source_card_id' in value) || value['source_card_id'] === undefined) return false;
    return true;
}

export function ExerciseResponseFromJSON(json: any): ExerciseResponse {
    return ExerciseResponseFromJSONTyped(json, false);
}

export function ExerciseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'level': json['level'],
        'instruction': json['instruction'],
        'prompt': json['prompt'],
        'correct_answer': json['correct_answer'],
        'hint': json['hint'] == null ? undefined : json['hint'],
        'source_sentence': json['source_sentence'] == null ? undefined : json['source_sentence'],
        'options': json['options'] == null ? undefined : json['options'],
        'data': json['data'] == null ? undefined : json['data'],
        'source_card_id': json['source_card_id'],
    };
}

export function ExerciseResponseToJSON(json: any): ExerciseResponse {
    return ExerciseResponseToJSONTyped(json, false);
}

export function ExerciseResponseToJSONTyped(value?: ExerciseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'level': value['level'],
        'instruction': value['instruction'],
        'prompt': value['prompt'],
        'correct_answer': value['correct_answer'],
        'hint': value['hint'],
        'source_sentence': value['source_sentence'],
        'options': value['options'],
        'data': value['data'],
        'source_card_id': value['source_card_id'],
    };
}

