/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { KnownWord } from "./KnownWord";
import {
  KnownWordFromJSON,
  KnownWordFromJSONTyped,
  KnownWordToJSON,
  KnownWordToJSONTyped,
} from "./KnownWord";
import type { ExerciseCard } from "./ExerciseCard";
import {
  ExerciseCardFromJSON,
  ExerciseCardFromJSONTyped,
  ExerciseCardToJSON,
  ExerciseCardToJSONTyped,
} from "./ExerciseCard";

/**
 *
 * @export
 * @interface ExerciseGenerateRequest
 */
export interface ExerciseGenerateRequest {
  /**
   *
   * @type {string}
   * @memberof ExerciseGenerateRequest
   */
  session_id?: string;
  /**
   *
   * @type {Array<ExerciseCard>}
   * @memberof ExerciseGenerateRequest
   */
  cards: Array<ExerciseCard>;
  /**
   *
   * @type {Array<KnownWord>}
   * @memberof ExerciseGenerateRequest
   */
  known_words?: Array<KnownWord>;
  /**
   *
   * @type {string}
   * @memberof ExerciseGenerateRequest
   */
  source_lang: string;
  /**
   *
   * @type {string}
   * @memberof ExerciseGenerateRequest
   */
  target_lang: string;
}

/**
 * Check if a given object implements the ExerciseGenerateRequest interface.
 */
export function instanceOfExerciseGenerateRequest(
  value: object,
): value is ExerciseGenerateRequest {
  if (!("cards" in value) || value["cards"] === undefined) return false;
  if (!("source_lang" in value) || value["source_lang"] === undefined)
    return false;
  if (!("target_lang" in value) || value["target_lang"] === undefined)
    return false;
  return true;
}

export function ExerciseGenerateRequestFromJSON(
  json: any,
): ExerciseGenerateRequest {
  return ExerciseGenerateRequestFromJSONTyped(json, false);
}

export function ExerciseGenerateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExerciseGenerateRequest {
  if (json == null) {
    return json;
  }
  return {
    session_id: json["session_id"] == null ? undefined : json["session_id"],
    cards: (json["cards"] as Array<any>).map(ExerciseCardFromJSON),
    known_words:
      json["known_words"] == null
        ? undefined
        : (json["known_words"] as Array<any>).map(KnownWordFromJSON),
    source_lang: json["source_lang"],
    target_lang: json["target_lang"],
  };
}

export function ExerciseGenerateRequestToJSON(
  json: any,
): ExerciseGenerateRequest {
  return ExerciseGenerateRequestToJSONTyped(json, false);
}

export function ExerciseGenerateRequestToJSONTyped(
  value?: ExerciseGenerateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    session_id: value["session_id"],
    cards: (value["cards"] as Array<any>).map(ExerciseCardToJSON),
    known_words:
      value["known_words"] == null
        ? undefined
        : (value["known_words"] as Array<any>).map(KnownWordToJSON),
    source_lang: value["source_lang"],
    target_lang: value["target_lang"],
  };
}
