/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GenerateRequest
 */
export interface GenerateRequest {
  /**
   *
   * @type {string}
   * @memberof GenerateRequest
   */
  prompt?: string;
  /**
   *
   * @type {string}
   * @memberof GenerateRequest
   */
  source_lang: string;
  /**
   *
   * @type {string}
   * @memberof GenerateRequest
   */
  target_lang: string;
  /**
   *
   * @type {string}
   * @memberof GenerateRequest
   */
  deck_id: string;
  /**
   *
   * @type {boolean}
   * @memberof GenerateRequest
   */
  generate_images?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GenerateRequest
   */
  from_deck?: boolean;
  /**
   *
   * @type {string}
   * @memberof GenerateRequest
   */
  mode?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof GenerateRequest
   */
  image_ids?: Array<string>;
}

/**
 * Check if a given object implements the GenerateRequest interface.
 */
export function instanceOfGenerateRequest(
  value: object,
): value is GenerateRequest {
  if (!("source_lang" in value) || value["source_lang"] === undefined)
    return false;
  if (!("target_lang" in value) || value["target_lang"] === undefined)
    return false;
  if (!("deck_id" in value) || value["deck_id"] === undefined) return false;
  return true;
}

export function GenerateRequestFromJSON(json: any): GenerateRequest {
  return GenerateRequestFromJSONTyped(json, false);
}

export function GenerateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GenerateRequest {
  if (json == null) {
    return json;
  }
  return {
    prompt: json["prompt"] == null ? undefined : json["prompt"],
    source_lang: json["source_lang"],
    target_lang: json["target_lang"],
    deck_id: json["deck_id"],
    generate_images:
      json["generate_images"] == null ? undefined : json["generate_images"],
    from_deck: json["from_deck"] == null ? undefined : json["from_deck"],
    mode: json["mode"] == null ? undefined : json["mode"],
    image_ids: json["image_ids"] == null ? undefined : json["image_ids"],
  };
}

export function GenerateRequestToJSON(json: any): GenerateRequest {
  return GenerateRequestToJSONTyped(json, false);
}

export function GenerateRequestToJSONTyped(
  value?: GenerateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prompt: value["prompt"],
    source_lang: value["source_lang"],
    target_lang: value["target_lang"],
    deck_id: value["deck_id"],
    generate_images: value["generate_images"],
    from_deck: value["from_deck"],
    mode: value["mode"],
    image_ids: value["image_ids"],
  };
}
