/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratedCard
 */
export interface GeneratedCard {
    /**
     * 
     * @type {string}
     * @memberof GeneratedCard
     */
    front: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedCard
     */
    back: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedCard
     */
    front_image_base64?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedCard
     */
    front_image_type?: string;
}

/**
 * Check if a given object implements the GeneratedCard interface.
 */
export function instanceOfGeneratedCard(value: object): value is GeneratedCard {
    if (!('front' in value) || value['front'] === undefined) return false;
    if (!('back' in value) || value['back'] === undefined) return false;
    return true;
}

export function GeneratedCardFromJSON(json: any): GeneratedCard {
    return GeneratedCardFromJSONTyped(json, false);
}

export function GeneratedCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratedCard {
    if (json == null) {
        return json;
    }
    return {
        
        'front': json['front'],
        'back': json['back'],
        'front_image_base64': json['front_image_base64'] == null ? undefined : json['front_image_base64'],
        'front_image_type': json['front_image_type'] == null ? undefined : json['front_image_type'],
    };
}

export function GeneratedCardToJSON(json: any): GeneratedCard {
    return GeneratedCardToJSONTyped(json, false);
}

export function GeneratedCardToJSONTyped(value?: GeneratedCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front': value['front'],
        'back': value['back'],
        'front_image_base64': value['front_image_base64'],
        'front_image_type': value['front_image_type'],
    };
}

