/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GradeResult
 */
export interface GradeResult {
    /**
     * 
     * @type {boolean}
     * @memberof GradeResult
     */
    correct: boolean;
    /**
     * 
     * @type {string}
     * @memberof GradeResult
     */
    feedback: string;
    /**
     * 
     * @type {string}
     * @memberof GradeResult
     */
    corrected_answer?: string;
}

/**
 * Check if a given object implements the GradeResult interface.
 */
export function instanceOfGradeResult(value: object): value is GradeResult {
    if (!('correct' in value) || value['correct'] === undefined) return false;
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    return true;
}

export function GradeResultFromJSON(json: any): GradeResult {
    return GradeResultFromJSONTyped(json, false);
}

export function GradeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GradeResult {
    if (json == null) {
        return json;
    }
    return {
        
        'correct': json['correct'],
        'feedback': json['feedback'],
        'corrected_answer': json['corrected_answer'] == null ? undefined : json['corrected_answer'],
    };
}

export function GradeResultToJSON(json: any): GradeResult {
    return GradeResultToJSONTyped(json, false);
}

export function GradeResultToJSONTyped(value?: GradeResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correct': value['correct'],
        'feedback': value['feedback'],
        'corrected_answer': value['corrected_answer'],
    };
}

