/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface KnownWord
 */
export interface KnownWord {
  /**
   *
   * @type {string}
   * @memberof KnownWord
   */
  front: string;
  /**
   *
   * @type {string}
   * @memberof KnownWord
   */
  back: string;
}

/**
 * Check if a given object implements the KnownWord interface.
 */
export function instanceOfKnownWord(value: object): value is KnownWord {
  if (!("front" in value) || value["front"] === undefined) return false;
  if (!("back" in value) || value["back"] === undefined) return false;
  return true;
}

export function KnownWordFromJSON(json: any): KnownWord {
  return KnownWordFromJSONTyped(json, false);
}

export function KnownWordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): KnownWord {
  if (json == null) {
    return json;
  }
  return {
    front: json["front"],
    back: json["back"],
  };
}

export function KnownWordToJSON(json: any): KnownWord {
  return KnownWordToJSONTyped(json, false);
}

export function KnownWordToJSONTyped(
  value?: KnownWord | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    front: value["front"],
    back: value["back"],
  };
}
