/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LanguagePairResponse
 */
export interface LanguagePairResponse {
  /**
   *
   * @type {string}
   * @memberof LanguagePairResponse
   */
  source_lang: string;
  /**
   *
   * @type {string}
   * @memberof LanguagePairResponse
   */
  target_lang: string;
  /**
   *
   * @type {string}
   * @memberof LanguagePairResponse
   */
  source_name: string;
  /**
   *
   * @type {string}
   * @memberof LanguagePairResponse
   */
  target_name: string;
}

/**
 * Check if a given object implements the LanguagePairResponse interface.
 */
export function instanceOfLanguagePairResponse(
  value: object,
): value is LanguagePairResponse {
  if (!("source_lang" in value) || value["source_lang"] === undefined)
    return false;
  if (!("target_lang" in value) || value["target_lang"] === undefined)
    return false;
  if (!("source_name" in value) || value["source_name"] === undefined)
    return false;
  if (!("target_name" in value) || value["target_name"] === undefined)
    return false;
  return true;
}

export function LanguagePairResponseFromJSON(json: any): LanguagePairResponse {
  return LanguagePairResponseFromJSONTyped(json, false);
}

export function LanguagePairResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LanguagePairResponse {
  if (json == null) {
    return json;
  }
  return {
    source_lang: json["source_lang"],
    target_lang: json["target_lang"],
    source_name: json["source_name"],
    target_name: json["target_name"],
  };
}

export function LanguagePairResponseToJSON(json: any): LanguagePairResponse {
  return LanguagePairResponseToJSONTyped(json, false);
}

export function LanguagePairResponseToJSONTyped(
  value?: LanguagePairResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    source_lang: value["source_lang"],
    target_lang: value["target_lang"],
    source_name: value["source_name"],
    target_name: value["target_name"],
  };
}
