/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReviewRequest
 */
export interface ReviewRequest {
  /**
   *
   * @type {string}
   * @memberof ReviewRequest
   */
  card_id: string;
  /**
   *
   * @type {number}
   * @memberof ReviewRequest
   */
  grade: number;
  /**
   *
   * @type {Date}
   * @memberof ReviewRequest
   */
  reviewed_at?: Date;
  /**
   *
   * @type {number}
   * @memberof ReviewRequest
   */
  response_time_ms?: number;
}

/**
 * Check if a given object implements the ReviewRequest interface.
 */
export function instanceOfReviewRequest(value: object): value is ReviewRequest {
  if (!("card_id" in value) || value["card_id"] === undefined) return false;
  if (!("grade" in value) || value["grade"] === undefined) return false;
  return true;
}

export function ReviewRequestFromJSON(json: any): ReviewRequest {
  return ReviewRequestFromJSONTyped(json, false);
}

export function ReviewRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReviewRequest {
  if (json == null) {
    return json;
  }
  return {
    card_id: json["card_id"],
    grade: json["grade"],
    reviewed_at:
      json["reviewed_at"] == null ? undefined : new Date(json["reviewed_at"]),
    response_time_ms:
      json["response_time_ms"] == null ? undefined : json["response_time_ms"],
  };
}

export function ReviewRequestToJSON(json: any): ReviewRequest {
  return ReviewRequestToJSONTyped(json, false);
}

export function ReviewRequestToJSONTyped(
  value?: ReviewRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    card_id: value["card_id"],
    grade: value["grade"],
    reviewed_at:
      value["reviewed_at"] == null
        ? value["reviewed_at"]
        : value["reviewed_at"].toISOString(),
    response_time_ms: value["response_time_ms"],
  };
}
