/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {
  /**
   *
   * @type {string}
   * @memberof StatusResponse
   */
  status: string;
}

/**
 * Check if a given object implements the StatusResponse interface.
 */
export function instanceOfStatusResponse(
  value: object,
): value is StatusResponse {
  if (!("status" in value) || value["status"] === undefined) return false;
  return true;
}

export function StatusResponseFromJSON(json: any): StatusResponse {
  return StatusResponseFromJSONTyped(json, false);
}

export function StatusResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StatusResponse {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
  };
}

export function StatusResponseToJSON(json: any): StatusResponse {
  return StatusResponseToJSONTyped(json, false);
}

export function StatusResponseToJSONTyped(
  value?: StatusResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
  };
}
