/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncAction } from './SyncAction';
import {
    SyncActionFromJSON,
    SyncActionFromJSONTyped,
    SyncActionToJSON,
    SyncActionToJSONTyped,
} from './SyncAction';

/**
 * 
 * @export
 * @interface SyncRequest
 */
export interface SyncRequest {
    /**
     * 
     * @type {Array<SyncAction>}
     * @memberof SyncRequest
     */
    actions: Array<SyncAction>;
}

/**
 * Check if a given object implements the SyncRequest interface.
 */
export function instanceOfSyncRequest(value: object): value is SyncRequest {
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function SyncRequestFromJSON(json: any): SyncRequest {
    return SyncRequestFromJSONTyped(json, false);
}

export function SyncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'actions': ((json['actions'] as Array<any>).map(SyncActionFromJSON)),
    };
}

export function SyncRequestToJSON(json: any): SyncRequest {
    return SyncRequestToJSONTyped(json, false);
}

export function SyncRequestToJSONTyped(value?: SyncRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actions': ((value['actions'] as Array<any>).map(SyncActionToJSON)),
    };
}

