/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncAction
 */
export interface SyncAction {
    /**
     * 
     * @type {string}
     * @memberof SyncAction
     */
    card_id: string;
    /**
     * 
     * @type {number}
     * @memberof SyncAction
     */
    grade: number;
    /**
     * 
     * @type {Date}
     * @memberof SyncAction
     */
    reviewed_at?: Date;
    /**
     * 
     * @type {number}
     * @memberof SyncAction
     */
    response_time_ms?: number;
}

/**
 * Check if a given object implements the SyncAction interface.
 */
export function instanceOfSyncAction(value: object): value is SyncAction {
    if (!('card_id' in value) || value['card_id'] === undefined) return false;
    if (!('grade' in value) || value['grade'] === undefined) return false;
    return true;
}

export function SyncActionFromJSON(json: any): SyncAction {
    return SyncActionFromJSONTyped(json, false);
}

export function SyncActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncAction {
    if (json == null) {
        return json;
    }
    return {
        
        'card_id': json['card_id'],
        'grade': json['grade'],
        'reviewed_at': json['reviewed_at'] == null ? undefined : (new Date(json['reviewed_at'])),
        'response_time_ms': json['response_time_ms'] == null ? undefined : json['response_time_ms'],
    };
}

export function SyncActionToJSON(json: any): SyncAction {
    return SyncActionToJSONTyped(json, false);
}

export function SyncActionToJSONTyped(value?: SyncAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card_id': value['card_id'],
        'grade': value['grade'],
        'reviewed_at': value['reviewed_at'] == null ? value['reviewed_at'] : value['reviewed_at'].toISOString(),
        'response_time_ms': value['response_time_ms'],
    };
}

