/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncResult
 */
export interface SyncResult {
    /**
     * 
     * @type {number}
     * @memberof SyncResult
     */
    processed: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SyncResult
     */
    errors?: Array<string>;
}

/**
 * Check if a given object implements the SyncResult interface.
 */
export function instanceOfSyncResult(value: object): value is SyncResult {
    if (!('processed' in value) || value['processed'] === undefined) return false;
    return true;
}

export function SyncResultFromJSON(json: any): SyncResult {
    return SyncResultFromJSONTyped(json, false);
}

export function SyncResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncResult {
    if (json == null) {
        return json;
    }
    return {
        
        'processed': json['processed'],
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function SyncResultToJSON(json: any): SyncResult {
    return SyncResultToJSONTyped(json, false);
}

export function SyncResultToJSONTyped(value?: SyncResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'processed': value['processed'],
        'errors': value['errors'],
    };
}

