/* tslint:disable */
/* eslint-disable */
/**
 * Langy API
 * Language learning flashcard API with spaced repetition
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateCardRequest
 */
export interface UpdateCardRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateCardRequest
   */
  front: string;
  /**
   *
   * @type {string}
   * @memberof UpdateCardRequest
   */
  back: string;
  /**
   *
   * @type {string}
   * @memberof UpdateCardRequest
   */
  front_image_id?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateCardRequest
   */
  back_image_id?: string;
}

/**
 * Check if a given object implements the UpdateCardRequest interface.
 */
export function instanceOfUpdateCardRequest(
  value: object,
): value is UpdateCardRequest {
  if (!("front" in value) || value["front"] === undefined) return false;
  if (!("back" in value) || value["back"] === undefined) return false;
  return true;
}

export function UpdateCardRequestFromJSON(json: any): UpdateCardRequest {
  return UpdateCardRequestFromJSONTyped(json, false);
}

export function UpdateCardRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCardRequest {
  if (json == null) {
    return json;
  }
  return {
    front: json["front"],
    back: json["back"],
    front_image_id:
      json["front_image_id"] == null ? undefined : json["front_image_id"],
    back_image_id:
      json["back_image_id"] == null ? undefined : json["back_image_id"],
  };
}

export function UpdateCardRequestToJSON(json: any): UpdateCardRequest {
  return UpdateCardRequestToJSONTyped(json, false);
}

export function UpdateCardRequestToJSONTyped(
  value?: UpdateCardRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    front: value["front"],
    back: value["back"],
    front_image_id: value["front_image_id"],
    back_image_id: value["back_image_id"],
  };
}
