// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (deck_id, front, back, front_image_id, back_image_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, deck_id, front, back,
	front_image_id, back_image_id,
	ease_factor, interval_days, repetitions, next_review, created_at, updated_at
`

type CreateCardParams struct {
	DeckID       pgtype.UUID
	Front        string
	Back         string
	FrontImageID pgtype.UUID
	BackImageID  pgtype.UUID
}

type CreateCardRow struct {
	ID           pgtype.UUID
	DeckID       pgtype.UUID
	Front        string
	Back         string
	FrontImageID pgtype.UUID
	BackImageID  pgtype.UUID
	EaseFactor   *float32
	IntervalDays *int32
	Repetitions  *int32
	NextReview   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (CreateCardRow, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.DeckID,
		arg.Front,
		arg.Back,
		arg.FrontImageID,
		arg.BackImageID,
	)
	var i CreateCardRow
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.FrontImageID,
		&i.BackImageID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :execrows
DELETE FROM cards USING decks
WHERE cards.deck_id = decks.id AND cards.id = $1 AND decks.user_id = $2
`

type DeleteCardParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCard, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCardForUser = `-- name: GetCardForUser :one
SELECT c.id, c.deck_id, c.front, c.back,
	c.front_image_id, c.back_image_id,
	c.ease_factor, c.interval_days, c.repetitions, c.next_review, c.created_at, c.updated_at
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE c.id = $1 AND d.user_id = $2
`

type GetCardForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetCardForUserRow struct {
	ID           pgtype.UUID
	DeckID       pgtype.UUID
	Front        string
	Back         string
	FrontImageID pgtype.UUID
	BackImageID  pgtype.UUID
	EaseFactor   *float32
	IntervalDays *int32
	Repetitions  *int32
	NextReview   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetCardForUser(ctx context.Context, arg GetCardForUserParams) (GetCardForUserRow, error) {
	row := q.db.QueryRow(ctx, getCardForUser, arg.ID, arg.UserID)
	var i GetCardForUserRow
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.FrontImageID,
		&i.BackImageID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardTexts = `-- name: ListCardTexts :many
SELECT c.front, c.back
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE c.deck_id = $1 AND d.user_id = $2
`

type ListCardTextsParams struct {
	DeckID pgtype.UUID
	UserID pgtype.UUID
}

type ListCardTextsRow struct {
	Front string
	Back  string
}

func (q *Queries) ListCardTexts(ctx context.Context, arg ListCardTextsParams) ([]ListCardTextsRow, error) {
	rows, err := q.db.Query(ctx, listCardTexts, arg.DeckID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardTextsRow
	for rows.Next() {
		var i ListCardTextsRow
		if err := rows.Scan(&i.Front, &i.Back); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCards = `-- name: ListCards :many
SELECT c.id, c.deck_id, c.front, c.back,
	c.front_image_id, c.back_image_id,
	c.ease_factor, c.interval_days, c.repetitions, c.next_review, c.created_at, c.updated_at
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE c.deck_id = $1 AND d.user_id = $2
ORDER BY c.created_at DESC
`

type ListCardsParams struct {
	DeckID pgtype.UUID
	UserID pgtype.UUID
}

type ListCardsRow struct {
	ID           pgtype.UUID
	DeckID       pgtype.UUID
	Front        string
	Back         string
	FrontImageID pgtype.UUID
	BackImageID  pgtype.UUID
	EaseFactor   *float32
	IntervalDays *int32
	Repetitions  *int32
	NextReview   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListCards(ctx context.Context, arg ListCardsParams) ([]ListCardsRow, error) {
	rows, err := q.db.Query(ctx, listCards, arg.DeckID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsRow
	for rows.Next() {
		var i ListCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.FrontImageID,
			&i.BackImageID,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :execrows
UPDATE cards SET front = $1, back = $2, front_image_id = $3, back_image_id = $4, updated_at = now()
FROM decks WHERE cards.deck_id = decks.id AND cards.id = $5 AND decks.user_id = $6
`

type UpdateCardParams struct {
	Front        string
	Back         string
	FrontImageID pgtype.UUID
	BackImageID  pgtype.UUID
	ID           pgtype.UUID
	UserID       pgtype.UUID
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCard,
		arg.Front,
		arg.Back,
		arg.FrontImageID,
		arg.BackImageID,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCardSRS = `-- name: UpdateCardSRS :exec
UPDATE cards SET ease_factor = $1, interval_days = $2, repetitions = $3,
	next_review = $4, updated_at = now()
WHERE id = $5
`

type UpdateCardSRSParams struct {
	EaseFactor   *float32
	IntervalDays *int32
	Repetitions  *int32
	NextReview   pgtype.Timestamptz
	ID           pgtype.UUID
}

func (q *Queries) UpdateCardSRS(ctx context.Context, arg UpdateCardSRSParams) error {
	_, err := q.db.Exec(ctx, updateCardSRS,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.Repetitions,
		arg.NextReview,
		arg.ID,
	)
	return err
}
