// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (deck_id, front, back)
VALUES ($1, $2, $3)
RETURNING id, deck_id, front, back,
	front_image, front_image_type, back_image, back_image_type,
	ease_factor, interval_days, repetitions, next_review, created_at, updated_at
`

type CreateCardParams struct {
	DeckID pgtype.UUID
	Front  string
	Back   string
}

type CreateCardRow struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (CreateCardRow, error) {
	row := q.db.QueryRow(ctx, createCard, arg.DeckID, arg.Front, arg.Back)
	var i CreateCardRow
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.FrontImage,
		&i.FrontImageType,
		&i.BackImage,
		&i.BackImageType,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCardWithAllImages = `-- name: CreateCardWithAllImages :one
INSERT INTO cards (deck_id, front, back, front_image, front_image_type, back_image, back_image_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, deck_id, front, back,
	front_image, front_image_type, back_image, back_image_type,
	ease_factor, interval_days, repetitions, next_review, created_at, updated_at
`

type CreateCardWithAllImagesParams struct {
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
}

type CreateCardWithAllImagesRow struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateCardWithAllImages(ctx context.Context, arg CreateCardWithAllImagesParams) (CreateCardWithAllImagesRow, error) {
	row := q.db.QueryRow(ctx, createCardWithAllImages,
		arg.DeckID,
		arg.Front,
		arg.Back,
		arg.FrontImage,
		arg.FrontImageType,
		arg.BackImage,
		arg.BackImageType,
	)
	var i CreateCardWithAllImagesRow
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.FrontImage,
		&i.FrontImageType,
		&i.BackImage,
		&i.BackImageType,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCardWithFrontImage = `-- name: CreateCardWithFrontImage :one
INSERT INTO cards (deck_id, front, back, front_image, front_image_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, deck_id, front, back,
	front_image, front_image_type, back_image, back_image_type,
	ease_factor, interval_days, repetitions, next_review, created_at, updated_at
`

type CreateCardWithFrontImageParams struct {
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
}

type CreateCardWithFrontImageRow struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateCardWithFrontImage(ctx context.Context, arg CreateCardWithFrontImageParams) (CreateCardWithFrontImageRow, error) {
	row := q.db.QueryRow(ctx, createCardWithFrontImage,
		arg.DeckID,
		arg.Front,
		arg.Back,
		arg.FrontImage,
		arg.FrontImageType,
	)
	var i CreateCardWithFrontImageRow
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.FrontImage,
		&i.FrontImageType,
		&i.BackImage,
		&i.BackImageType,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :execrows
DELETE FROM cards USING decks
WHERE cards.deck_id = decks.id AND cards.id = $1 AND decks.user_id = $2
`

type DeleteCardParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCard, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCardForUser = `-- name: GetCardForUser :one
SELECT c.id, c.deck_id, c.front, c.back,
	c.front_image, c.front_image_type, c.back_image, c.back_image_type,
	c.ease_factor, c.interval_days, c.repetitions, c.next_review, c.created_at, c.updated_at
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE c.id = $1 AND d.user_id = $2
`

type GetCardForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetCardForUserRow struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetCardForUser(ctx context.Context, arg GetCardForUserParams) (GetCardForUserRow, error) {
	row := q.db.QueryRow(ctx, getCardForUser, arg.ID, arg.UserID)
	var i GetCardForUserRow
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.FrontImage,
		&i.FrontImageType,
		&i.BackImage,
		&i.BackImageType,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardTexts = `-- name: ListCardTexts :many
SELECT c.front, c.back
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE c.deck_id = $1 AND d.user_id = $2
`

type ListCardTextsParams struct {
	DeckID pgtype.UUID
	UserID pgtype.UUID
}

type ListCardTextsRow struct {
	Front string
	Back  string
}

func (q *Queries) ListCardTexts(ctx context.Context, arg ListCardTextsParams) ([]ListCardTextsRow, error) {
	rows, err := q.db.Query(ctx, listCardTexts, arg.DeckID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardTextsRow
	for rows.Next() {
		var i ListCardTextsRow
		if err := rows.Scan(&i.Front, &i.Back); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCards = `-- name: ListCards :many
SELECT c.id, c.deck_id, c.front, c.back,
	c.front_image, c.front_image_type, c.back_image, c.back_image_type,
	c.ease_factor, c.interval_days, c.repetitions, c.next_review, c.created_at, c.updated_at
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE c.deck_id = $1 AND d.user_id = $2
ORDER BY c.created_at DESC
`

type ListCardsParams struct {
	DeckID pgtype.UUID
	UserID pgtype.UUID
}

type ListCardsRow struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListCards(ctx context.Context, arg ListCardsParams) ([]ListCardsRow, error) {
	rows, err := q.db.Query(ctx, listCards, arg.DeckID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsRow
	for rows.Next() {
		var i ListCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.FrontImage,
			&i.FrontImageType,
			&i.BackImage,
			&i.BackImageType,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardSRS = `-- name: UpdateCardSRS :exec
UPDATE cards SET ease_factor = $1, interval_days = $2, repetitions = $3,
	next_review = $4, updated_at = now()
WHERE id = $5
`

type UpdateCardSRSParams struct {
	EaseFactor   *float32
	IntervalDays *int32
	Repetitions  *int32
	NextReview   pgtype.Timestamptz
	ID           pgtype.UUID
}

func (q *Queries) UpdateCardSRS(ctx context.Context, arg UpdateCardSRSParams) error {
	_, err := q.db.Exec(ctx, updateCardSRS,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.Repetitions,
		arg.NextReview,
		arg.ID,
	)
	return err
}

const updateCardText = `-- name: UpdateCardText :execrows
UPDATE cards SET front = $1, back = $2, updated_at = now()
FROM decks WHERE cards.deck_id = decks.id AND cards.id = $3 AND decks.user_id = $4
`

type UpdateCardTextParams struct {
	Front  string
	Back   string
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) UpdateCardText(ctx context.Context, arg UpdateCardTextParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardText,
		arg.Front,
		arg.Back,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCardWithBackImage = `-- name: UpdateCardWithBackImage :execrows
UPDATE cards SET front = $1, back = $2, back_image = $3, back_image_type = $4, updated_at = now()
FROM decks WHERE cards.deck_id = decks.id AND cards.id = $5 AND decks.user_id = $6
`

type UpdateCardWithBackImageParams struct {
	Front         string
	Back          string
	BackImage     []byte
	BackImageType *string
	ID            pgtype.UUID
	UserID        pgtype.UUID
}

func (q *Queries) UpdateCardWithBackImage(ctx context.Context, arg UpdateCardWithBackImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardWithBackImage,
		arg.Front,
		arg.Back,
		arg.BackImage,
		arg.BackImageType,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCardWithBothImages = `-- name: UpdateCardWithBothImages :execrows
UPDATE cards SET front = $1, back = $2, front_image = $3, front_image_type = $4, back_image = $5, back_image_type = $6, updated_at = now()
FROM decks WHERE cards.deck_id = decks.id AND cards.id = $7 AND decks.user_id = $8
`

type UpdateCardWithBothImagesParams struct {
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	ID             pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) UpdateCardWithBothImages(ctx context.Context, arg UpdateCardWithBothImagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardWithBothImages,
		arg.Front,
		arg.Back,
		arg.FrontImage,
		arg.FrontImageType,
		arg.BackImage,
		arg.BackImageType,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCardWithFrontImage = `-- name: UpdateCardWithFrontImage :execrows
UPDATE cards SET front = $1, back = $2, front_image = $3, front_image_type = $4, updated_at = now()
FROM decks WHERE cards.deck_id = decks.id AND cards.id = $5 AND decks.user_id = $6
`

type UpdateCardWithFrontImageParams struct {
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	ID             pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) UpdateCardWithFrontImage(ctx context.Context, arg UpdateCardWithFrontImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardWithFrontImage,
		arg.Front,
		arg.Back,
		arg.FrontImage,
		arg.FrontImageType,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
