// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (user_id, name, source_lang, target_lang) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, source_lang, target_lang, created_at
`

type CreateDeckParams struct {
	UserID     pgtype.UUID
	Name       string
	SourceLang string
	TargetLang string
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (SqlcDeck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.SourceLang,
		arg.TargetLang,
	)
	var i SqlcDeck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SourceLang,
		&i.TargetLang,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :execrows
DELETE FROM decks WHERE id = $1 AND user_id = $2
`

type DeleteDeckParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteDeck(ctx context.Context, arg DeleteDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeck, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeck = `-- name: GetDeck :one
SELECT id, user_id, name, source_lang, target_lang, created_at
FROM decks WHERE id = $1 AND user_id = $2
`

type GetDeckParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetDeck(ctx context.Context, arg GetDeckParams) (SqlcDeck, error) {
	row := q.db.QueryRow(ctx, getDeck, arg.ID, arg.UserID)
	var i SqlcDeck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SourceLang,
		&i.TargetLang,
		&i.CreatedAt,
	)
	return i, err
}

const listDecks = `-- name: ListDecks :many
SELECT id, user_id, name, source_lang, target_lang, created_at
FROM decks WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDecks(ctx context.Context, userID pgtype.UUID) ([]SqlcDeck, error) {
	rows, err := q.db.Query(ctx, listDecks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SqlcDeck
	for rows.Next() {
		var i SqlcDeck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SourceLang,
			&i.TargetLang,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
