// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCardsNeedingExercises = `-- name: GetCardsNeedingExercises :many
SELECT dk.user_id, c.id AS card_id, c.front, c.back, c.repetitions, c.interval_days, dk.source_lang, dk.target_lang
FROM cards c
JOIN decks dk ON c.deck_id = dk.id
WHERE NOT EXISTS (
	SELECT 1 FROM exercises e WHERE e.source_card_id = c.id AND e.completed = false
)
ORDER BY random()
LIMIT $1
`

type GetCardsNeedingExercisesRow struct {
	UserID       pgtype.UUID
	CardID       pgtype.UUID
	Front        string
	Back         string
	Repetitions  *int32
	IntervalDays *int32
	SourceLang   string
	TargetLang   string
}

func (q *Queries) GetCardsNeedingExercises(ctx context.Context, limit int32) ([]GetCardsNeedingExercisesRow, error) {
	rows, err := q.db.Query(ctx, getCardsNeedingExercises, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardsNeedingExercisesRow
	for rows.Next() {
		var i GetCardsNeedingExercisesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CardID,
			&i.Front,
			&i.Back,
			&i.Repetitions,
			&i.IntervalDays,
			&i.SourceLang,
			&i.TargetLang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDueExercises = `-- name: GetDueExercises :many
SELECT e.id, e.user_id, e.session_id, e.source_card_id, e.type, e.level, e.instruction, e.prompt, e.correct_answer, e.hint, e.source_sentence, e.options, e.data, e.completed, e.user_answer, e.correct, e.feedback, e.next_review, e.created_at
FROM exercises e
WHERE e.user_id = $1 AND e.correct = false AND e.next_review <= now()
ORDER BY e.next_review ASC
`

type GetDueExercisesRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	SessionID      pgtype.UUID
	SourceCardID   pgtype.UUID
	Type           string
	Level          int32
	Instruction    string
	Prompt         string
	CorrectAnswer  string
	Hint           *string
	SourceSentence *string
	Options        []byte
	Data           []byte
	Completed      *bool
	UserAnswer     *string
	Correct        *bool
	Feedback       *string
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetDueExercises(ctx context.Context, userID pgtype.UUID) ([]GetDueExercisesRow, error) {
	rows, err := q.db.Query(ctx, getDueExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueExercisesRow
	for rows.Next() {
		var i GetDueExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.SourceCardID,
			&i.Type,
			&i.Level,
			&i.Instruction,
			&i.Prompt,
			&i.CorrectAnswer,
			&i.Hint,
			&i.SourceSentence,
			&i.Options,
			&i.Data,
			&i.Completed,
			&i.UserAnswer,
			&i.Correct,
			&i.Feedback,
			&i.NextReview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUncompletedExercises = `-- name: GetUncompletedExercises :many
SELECT e.id, e.user_id, e.session_id, e.source_card_id, e.type, e.level, e.instruction, e.prompt, e.correct_answer, e.hint, e.source_sentence, e.options, e.data, e.completed, e.user_answer, e.correct, e.feedback, e.next_review, e.created_at
FROM exercises e
WHERE e.user_id = $1 AND e.completed = false
ORDER BY e.created_at ASC
`

type GetUncompletedExercisesRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	SessionID      pgtype.UUID
	SourceCardID   pgtype.UUID
	Type           string
	Level          int32
	Instruction    string
	Prompt         string
	CorrectAnswer  string
	Hint           *string
	SourceSentence *string
	Options        []byte
	Data           []byte
	Completed      *bool
	UserAnswer     *string
	Correct        *bool
	Feedback       *string
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetUncompletedExercises(ctx context.Context, userID pgtype.UUID) ([]GetUncompletedExercisesRow, error) {
	rows, err := q.db.Query(ctx, getUncompletedExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUncompletedExercisesRow
	for rows.Next() {
		var i GetUncompletedExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.SourceCardID,
			&i.Type,
			&i.Level,
			&i.Instruction,
			&i.Prompt,
			&i.CorrectAnswer,
			&i.Hint,
			&i.SourceSentence,
			&i.Options,
			&i.Data,
			&i.Completed,
			&i.UserAnswer,
			&i.Correct,
			&i.Feedback,
			&i.NextReview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveExercise = `-- name: SaveExercise :one
INSERT INTO exercises (user_id, session_id, source_card_id, type, level, instruction, prompt, correct_answer, hint, source_sentence, options, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, session_id, source_card_id, type, level, instruction, prompt, correct_answer, hint, source_sentence, options, data, completed, user_answer, correct, feedback, next_review, created_at
`

type SaveExerciseParams struct {
	UserID         pgtype.UUID
	SessionID      pgtype.UUID
	SourceCardID   pgtype.UUID
	Type           string
	Level          int32
	Instruction    string
	Prompt         string
	CorrectAnswer  string
	Hint           *string
	SourceSentence *string
	Options        []byte
	Data           []byte
}

type SaveExerciseRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	SessionID      pgtype.UUID
	SourceCardID   pgtype.UUID
	Type           string
	Level          int32
	Instruction    string
	Prompt         string
	CorrectAnswer  string
	Hint           *string
	SourceSentence *string
	Options        []byte
	Data           []byte
	Completed      *bool
	UserAnswer     *string
	Correct        *bool
	Feedback       *string
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) SaveExercise(ctx context.Context, arg SaveExerciseParams) (SaveExerciseRow, error) {
	row := q.db.QueryRow(ctx, saveExercise,
		arg.UserID,
		arg.SessionID,
		arg.SourceCardID,
		arg.Type,
		arg.Level,
		arg.Instruction,
		arg.Prompt,
		arg.CorrectAnswer,
		arg.Hint,
		arg.SourceSentence,
		arg.Options,
		arg.Data,
	)
	var i SaveExerciseRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.SourceCardID,
		&i.Type,
		&i.Level,
		&i.Instruction,
		&i.Prompt,
		&i.CorrectAnswer,
		&i.Hint,
		&i.SourceSentence,
		&i.Options,
		&i.Data,
		&i.Completed,
		&i.UserAnswer,
		&i.Correct,
		&i.Feedback,
		&i.NextReview,
		&i.CreatedAt,
	)
	return i, err
}

const updateExerciseResultCorrect = `-- name: UpdateExerciseResultCorrect :execrows
UPDATE exercises SET completed = true, user_answer = $1, correct = $2, feedback = $3
FROM cards c JOIN decks dk ON c.deck_id = dk.id
WHERE exercises.source_card_id = c.id AND dk.user_id = $4 AND exercises.id = $5
`

type UpdateExerciseResultCorrectParams struct {
	UserAnswer *string
	Correct    *bool
	Feedback   *string
	UserID     pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) UpdateExerciseResultCorrect(ctx context.Context, arg UpdateExerciseResultCorrectParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExerciseResultCorrect,
		arg.UserAnswer,
		arg.Correct,
		arg.Feedback,
		arg.UserID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExerciseResultIncorrect = `-- name: UpdateExerciseResultIncorrect :execrows
UPDATE exercises SET completed = true, user_answer = $1, correct = $2, feedback = $3, next_review = now() + interval '2 days'
FROM cards c JOIN decks dk ON c.deck_id = dk.id
WHERE exercises.source_card_id = c.id AND dk.user_id = $4 AND exercises.id = $5
`

type UpdateExerciseResultIncorrectParams struct {
	UserAnswer *string
	Correct    *bool
	Feedback   *string
	UserID     pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) UpdateExerciseResultIncorrect(ctx context.Context, arg UpdateExerciseResultIncorrectParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExerciseResultIncorrect,
		arg.UserAnswer,
		arg.Correct,
		arg.Feedback,
		arg.UserID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
