// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (user_id, data, content_type)
VALUES ($1, $2, $3)
RETURNING id, user_id, content_type, created_at
`

type CreateImageParams struct {
	UserID      pgtype.UUID
	Data        []byte
	ContentType string
}

type CreateImageRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	ContentType string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (CreateImageRow, error) {
	row := q.db.QueryRow(ctx, createImage, arg.UserID, arg.Data, arg.ContentType)
	var i CreateImageRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrphanedImages = `-- name: DeleteOrphanedImages :exec
DELETE FROM images
WHERE id NOT IN (
	SELECT front_image_id FROM cards WHERE front_image_id IS NOT NULL
	UNION
	SELECT back_image_id FROM cards WHERE back_image_id IS NOT NULL
)
AND created_at < now() - interval '1 hour'
`

func (q *Queries) DeleteOrphanedImages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOrphanedImages)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, user_id, data, content_type, created_at
FROM images WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id pgtype.UUID) (SqlcImage, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i SqlcImage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}
