// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SqlcCard struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
}

type SqlcDeck struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	SourceLang string
	TargetLang string
	CreatedAt  pgtype.Timestamptz
}

type SqlcExercise struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	SessionID      pgtype.UUID
	SourceCardID   pgtype.UUID
	Type           string
	Level          int32
	Instruction    string
	Prompt         string
	CorrectAnswer  string
	Hint           *string
	Options        []byte
	Completed      *bool
	UserAnswer     *string
	Correct        *bool
	Feedback       *string
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	SourceSentence *string
	Data           []byte
}

type SqlcReviewLog struct {
	ID             pgtype.UUID
	CardID         pgtype.UUID
	UserID         pgtype.UUID
	Grade          int32
	ReviewedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	ResponseTimeMs *int32
}

type SqlcUser struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
