// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReviewLog = `-- name: CreateReviewLog :exec
INSERT INTO review_logs (card_id, user_id, grade, reviewed_at, response_time_ms)
VALUES ($1, $2, $3, $4, $5)
`

type CreateReviewLogParams struct {
	CardID         pgtype.UUID
	UserID         pgtype.UUID
	Grade          int32
	ReviewedAt     pgtype.Timestamptz
	ResponseTimeMs *int32
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) error {
	_, err := q.db.Exec(ctx, createReviewLog,
		arg.CardID,
		arg.UserID,
		arg.Grade,
		arg.ReviewedAt,
		arg.ResponseTimeMs,
	)
	return err
}

const getDueCards = `-- name: GetDueCards :many
SELECT c.id, c.deck_id, c.front, c.back,
	c.front_image, c.front_image_type, c.back_image, c.back_image_type,
	c.ease_factor, c.interval_days, c.repetitions, c.next_review, c.created_at, c.updated_at
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE d.user_id = $1 AND c.next_review <= now() AND c.repetitions > 0
	AND ($2::uuid IS NULL OR c.deck_id = $2::uuid)
ORDER BY c.next_review ASC
`

type GetDueCardsParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

type GetDueCardsRow struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetDueCards(ctx context.Context, arg GetDueCardsParams) ([]GetDueCardsRow, error) {
	rows, err := q.db.Query(ctx, getDueCards, arg.UserID, arg.DeckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueCardsRow
	for rows.Next() {
		var i GetDueCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.FrontImage,
			&i.FrontImageType,
			&i.BackImage,
			&i.BackImageType,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewCards = `-- name: GetNewCards :many
SELECT c.id, c.deck_id, c.front, c.back,
	c.front_image, c.front_image_type, c.back_image, c.back_image_type,
	c.ease_factor, c.interval_days, c.repetitions, c.next_review, c.created_at, c.updated_at
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE d.user_id = $1 AND c.repetitions = 0
	AND ($2::uuid IS NULL OR c.deck_id = $2::uuid)
ORDER BY c.created_at ASC
`

type GetNewCardsParams struct {
	UserID pgtype.UUID
	DeckID pgtype.UUID
}

type GetNewCardsRow struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetNewCards(ctx context.Context, arg GetNewCardsParams) ([]GetNewCardsRow, error) {
	rows, err := q.db.Query(ctx, getNewCards, arg.UserID, arg.DeckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewCardsRow
	for rows.Next() {
		var i GetNewCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.FrontImage,
			&i.FrontImageType,
			&i.BackImage,
			&i.BackImageType,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingCards = `-- name: GetUpcomingCards :many
SELECT c.id, c.deck_id, c.front, c.back,
	c.front_image, c.front_image_type, c.back_image, c.back_image_type,
	c.ease_factor, c.interval_days, c.repetitions, c.next_review, c.created_at, c.updated_at
FROM cards c JOIN decks d ON c.deck_id = d.id
WHERE d.user_id = $1 AND c.repetitions > 0 AND c.next_review > now()
	AND c.id != ALL($2::uuid[])
	AND ($4::uuid IS NULL OR c.deck_id = $4::uuid)
ORDER BY c.next_review ASC
LIMIT $3
`

type GetUpcomingCardsParams struct {
	UserID  pgtype.UUID
	Column2 []pgtype.UUID
	Limit   int32
	DeckID  pgtype.UUID
}

type GetUpcomingCardsRow struct {
	ID             pgtype.UUID
	DeckID         pgtype.UUID
	Front          string
	Back           string
	FrontImage     []byte
	FrontImageType *string
	BackImage      []byte
	BackImageType  *string
	EaseFactor     *float32
	IntervalDays   *int32
	Repetitions    *int32
	NextReview     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetUpcomingCards(ctx context.Context, arg GetUpcomingCardsParams) ([]GetUpcomingCardsRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingCards,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.DeckID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingCardsRow
	for rows.Next() {
		var i GetUpcomingCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.FrontImage,
			&i.FrontImageType,
			&i.BackImage,
			&i.BackImageType,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
